# ********RoostGPT********

# Test generated by RoostGPT for test IntegrationTestExample using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=faadb96ba0
# ROOST_METHOD_SIG_HASH=2ca47391fe
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Collection Agency Involvement',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send a POST request to '/collection-agency' with body\n" +
#       '    """\n' +
#       '    {\n' +
#       '        "previousNotifications": "3",\n' +
#       '        "responseStatus": "No response",\n' +
#       '        "cardLast4": "1234"\n' +
#       '    }\n' +
#       'Then the response status should be 200\n' +
#       "And the response should contain 'Collection agency now involved for credit card ending with 1234.'",
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Collection Agency Involvement
    * url ZBIO_5213_026A11B060_URL
    Given path '/collection-agency'
    And request
      """
      { 
        previousNotifications: '3', 
        responseStatus: 'No response', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200
    And match response contains 'Collection agency now involved for credit card ending with 1234.'
    And match response == '#string'
