# ********RoostGPT********

# Test generated by RoostGPT for test apikarate using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=ef15eed2d4
# ROOST_METHOD_SIG_HASH=292761d0a2
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Collection Notification',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send a POST request to '/collection-notification' with body\n" +
#       '    """\n' +
#       '    {\n' +
#       '        "delinquencyStatus": "60 days overdue",\n' +
#       '        "outstandingBalance": "$350.00",\n' +
#       '        "additionalCharges": "$50.00",\n' +
#       '        "cardLast4": "1234"\n' +
#       '    }\n' +
#       'Then the response status should be 200\n' +
#       "And the response should contain 'Your account has become significantly delinquent. Please contact us immediately to avoid further charges.'",
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Collection Notification
    * url ZBIO_5213_026A11B060_URL
    Given path '/collection-notification'
    And request
      """
      { 
        "delinquencyStatus": "60 days overdue", 
        "outstandingBalance": "$350.00", 
        "additionalCharges": "$50.00", 
        "cardLast4": "1234" 
      }
      """
    When method post
    Then status 200
    And match response == '#string'
    And match response contains 'Your account has become significantly delinquent. Please contact us immediately to avoid further charges.'
