# ********RoostGPT********

# Test generated by RoostGPT for test apikarate using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=97540f287b
# ROOST_METHOD_SIG_HASH=c38438829f
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Compatibility Testing',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       'When I send notifications through supported platforms\n' +
#       'Then the notifications should display as expected on each platform',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Test GET /notifications
    * url ZBIO_5213_026A11B060_URL
    And path '/notifications'
    When method get
    Then status 200
    And match response == '#object'

  Scenario: Test GET /card-details
    * url ZBIO_5213_026A11B060_URL
    And path '/card-details'
    When method get
    Then status 200
    And match response.cardNumberPartial == '#string'

  Scenario: Test POST /payment-reminder
    * url ZBIO_5213_026A11B060_URL
    And path '/payment-reminder'
    And request
      """
      { 
        currentDate: '2023-10-30', 
        paymentDueDate: '2023-11-15', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test POST /balance-alert
    * url ZBIO_5213_026A11B060_URL
    And path '/balance-alert'
    And request
      """
      { 
        paymentDueDate: '2023-11-15', 
        currentDate: '2023-10-30', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test POST /collection-notification
    * url ZBIO_5213_026A11B060_URL
    And path '/collection-notification'
    And request
      """
      { 
        delinquencyStatus: 'Overdue', 
        outstandingBalance: '500', 
        additionalCharges: '50', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test POST /payment-plan-proposal
    * url ZBIO_5213_026A11B060_URL
    And path '/payment-plan-proposal'
    And request
      """
      { 
        outstandingBalance: '500', 
        paymentPlan: { 
          installmentAmount: '50', 
          interestRate: '5', 
          termLength: '10'
        }, 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test POST /collection-agency
    * url ZBIO_5213_026A11B060_URL
    And path '/collection-agency'
    And request
      """
      { 
        previousNotifications: 'Yes', 
        responseStatus: 'Pending', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test POST /legal-action
    * url ZBIO_5213_026A11B060_URL
    And path '/legal-action'
    And request
      """
      { 
        nonPaymentStatus: 'Confirmed', 
        legalStatus: 'Initiated', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200
