# ********RoostGPT********

# Test generated by RoostGPT for test IntegrationTestExample using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=97540f287b
# ROOST_METHOD_SIG_HASH=c38438829f
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Compatibility Testing',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       'When I send notifications through supported platforms\n' +
#       'Then the notifications should display as expected on each platform',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Test Payment Reminder API
    * url ZBIO_5213_026A11B060_URL
    And path '/payment-reminder'
    And request
      """
      { 
        currentDate: '2023-10-01', 
        paymentDueDate: '2023-10-15', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test Balance Alert API
    * url ZBIO_5213_026A11B060_URL
    And path '/balance-alert'
    And request
      """
      { 
        paymentDueDate: '2023-10-15', 
        currentDate: '2023-10-01', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test Collection Notification API
    * url ZBIO_5213_026A11B060_URL
    And path '/collection-notification'
    And request
      """
      { 
        delinquencyStatus: 'delinquent', 
        outstandingBalance: '500', 
        additionalCharges: '50', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test Payment Plan Proposal API
    * url ZBIO_5213_026A11B060_URL
    And path '/payment-plan-proposal'
    And request
      """
      { 
        outstandingBalance: '500', 
        paymentPlan: { 
          installmentAmount: '50', 
          interestRate: '5', 
          termLength: '10' 
        }, 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test Collection Agency API
    * url ZBIO_5213_026A11B060_URL
    And path '/collection-agency'
    And request
      """
      { 
        previousNotifications: 'none', 
        responseStatus: 'pending', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Test Legal Action API
    * url ZBIO_5213_026A11B060_URL
    And path '/legal-action'
    And request
      """
      { 
        nonPaymentStatus: 'unpaid', 
        legalStatus: 'pending', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200

  Scenario: Retrieve Notifications
    * url ZBIO_5213_026A11B060_URL
    And path '/notifications'
    When method get
    Then status 200
    And match response == '#object'

  Scenario: Retrieve Card Details
    * url ZBIO_5213_026A11B060_URL
    And path '/card-details'
    When method get
    Then status 200
    And match response.cardNumberPartial == '#string'
