# ********RoostGPT********

# Test generated by RoostGPT for test apikarate using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=238d1ceec2
# ROOST_METHOD_SIG_HASH=9d5614a5b1
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Credit Card Due Reminder',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send a POST request to '/payment-reminder' with body\n" +
#       '    """\n' +
#       '    {\n' +
#       '        "currentDate": "2022-07-14",\n' +
#       '        "paymentDueDate": "2022-07-15",\n' +
#       '        "cardLast4": "1234"\n' +
#       '    }\n' +
#       'Then the response status should be 200\n' +
#       "And the response should contain 'Reminder about the payment due date for your card ending in 1234.'",
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Credit Card Due Reminder
    * url ZBIO_5213_026A11B060_URL
    Given path '/payment-reminder'
    And request
      """
      { 
        "currentDate": "2022-07-14", 
        "paymentDueDate": "2022-07-15", 
        "cardLast4": "1234" 
      }
      """
    When method post
    Then status 200
    And match response == '#string'
    And match response contains 'Reminder about the payment due date for your card ending in 1234.'
