# ********RoostGPT********

# Test generated by RoostGPT for test apikarate using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=9f19b46bae
# ROOST_METHOD_SIG_HASH=f4b3d3b75c
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Legal Action Initiation',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send a POST request to '/legal-action' with body\n" +
#       '    """\n' +
#       '    {\n' +
#       '        "nonPaymentStatus": "90 days overdue",\n' +
#       '        "legalStatus": "Notice served",\n' +
#       '        "cardLast4": "1234"\n' +
#       '    }\n' +
#       'Then the response status should be 200\n' +
#       "And the response should contain 'Legal action initiated for credit card ending with 1234.'",
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')
    * def ZBIO_5213_026A11B060_AUTH_TOKEN = karate.properties['ZBIO_5213_026A11B060_AUTH_TOKEN'] || karate.get('ZBIO_5213_026A11B060_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario: Legal Action Initiation
    * url ZBIO_5213_026A11B060_URL
    Given path '/legal-action'
    * configure headers = { Authorization: ZBIO_5213_026A11B060_AUTH_TOKEN }
    And request
      """
      { nonPaymentStatus: '90 days overdue', legalStatus: 'Notice served', cardLast4: '1234' }
      """
    When method post
    Then status 200
    And match response == '#string'
    And match response contains 'Legal action initiated for credit card ending with'

  Scenario: Legal Action Initiation with Invalid Card Number
    * url ZBIO_5213_026A11B060_URL
    Given path '/legal-action'
    * configure headers = { Authorization: ZBIO_5213_026A11B060_AUTH_TOKEN }
    And request
      """
      { nonPaymentStatus: '90 days overdue', legalStatus: 'Notice served', cardLast4: '0000' }
      """
    When method post
    Then status 400
    And match response == '#string'
    And match response contains 'Invalid card number'

  Scenario: Legal Action Initiation with Missing Fields
    * url ZBIO_5213_026A11B060_URL
    Given path '/legal-action'
    * configure headers = { Authorization: ZBIO_5213_026A11B060_AUTH_TOKEN }
    And request
      """
      { nonPaymentStatus: '90 days overdue', cardLast4: '1234' }
      """
    When method post
    Then status 400
    And match response == '#string'
    And match response contains 'Missing required fields'
