# ********RoostGPT********

# Test generated by RoostGPT for test apikarate using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=4300602fd1
# ROOST_METHOD_SIG_HASH=1daa477c64
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Overdue Balance Alert',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send a POST request to '/balance-alert' with body\n" +
#       '    """\n' +
#       '    {\n' +
#       '        "paymentDueDate": "2022-07-15",\n' +
#       '        "currentDate": "2022-07-16",\n' +
#       '        "cardLast4": "1234"\n' +
#       '    }\n' +
#       'Then the response status should be 200\n' +
#       "And the response should contain 'You have overdue balance for your card ending in 1234. Please make payment immediately to avoid charges.'",
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Overdue Balance Alert
    * url ZBIO_5213_026A11B060_URL
    Given path '/balance-alert'
    And request
      """
      { 
        paymentDueDate: '2022-07-15', 
        currentDate: '2022-07-16', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200
    And match response == '#string'
    And match response contains 'You have overdue balance for your card ending in 1234. Please make payment immediately to avoid charges.'

  Scenario: Invalid Card Number
    * url ZBIO_5213_026A11B060_URL
    Given path '/balance-alert'
    And request
      """
      { 
        paymentDueDate: '2022-07-15', 
        currentDate: '2022-07-16', 
        cardLast4: '12' 
      }
      """
    When method post
    Then status 400
    And match response == '#string'
    And match response contains 'Invalid card number'

  Scenario: Missing Payment Due Date
    * url ZBIO_5213_026A11B060_URL
    Given path '/balance-alert'
    And request
      """
      { 
        currentDate: '2022-07-16', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 400
    And match response == '#string'
    And match response contains 'Missing required field: paymentDueDate'

  Scenario: Future Payment Due Date
    * url ZBIO_5213_026A11B060_URL
    Given path '/balance-alert'
    And request
      """
      { 
        paymentDueDate: '2023-07-15', 
        currentDate: '2022-07-16', 
        cardLast4: '1234' 
      }
      """
    When method post
    Then status 200
    And match response == '#string'
    And match response contains 'Your payment due date is in the future. No action required.'
