# ********RoostGPT********

# Test generated by RoostGPT for test apikarate using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=a21f050c75
# ROOST_METHOD_SIG_HASH=f73255e8f9
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Payment Plan Proposal',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send a POST request to '/payment-plan-proposal' with body\n" +
#       '    """\n' +
#       '    {\n' +
#       '        "outstandingBalance": "$350.00",\n' +
#       '        "paymentPlan": {\n' +
#       '            "installmentAmount": "$50.00",\n' +
#       '            "interestRate": "6%",\n' +
#       '            "termLength": "6 months"\n' +
#       '        },\n' +
#       '        "cardLast4": "1234"\n' +
#       '    }\n' +
#       'Then the response status should be 200\n' +
#       "And the response should contain 'We propose a payment plan for your card ending in 1234. Please review it and respond promptly.'",
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Payment Plan Proposal
    * url ZBIO_5213_026A11B060_URL
    And path '/payment-plan-proposal'
    And request
      """
      {
          "outstandingBalance": "$350.00",
          "paymentPlan": {
              "installmentAmount": "$50.00",
              "interestRate": "6%",
              "termLength": "6 months"
          },
          "cardLast4": "1234"
      }
      """
    When method post
    Then status 200
    And match response == '#string'
    And match response contains 'We propose a payment plan for your card ending in 1234. Please review it and respond promptly.'
