# ********RoostGPT********

# Test generated by RoostGPT for test IntegrationTestExample using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=8bfe8ad67f
# ROOST_METHOD_SIG_HASH=1d82761590
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Performance Testing',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send multiple simultaneous requests to '/notifications'\n" +
#       'Then the response status for each request should be 200',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Performance Testing
    * url ZBIO_5213_026A11B060_URL
    Given path '/notifications'
    When method get
    Then status 200
    And match response == '#object'
