# ********RoostGPT********

# Test generated by RoostGPT for test IntegrationTestExample using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=520e98f743
# ROOST_METHOD_SIG_HASH=238b0fb140
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Security Testing',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send a GET request to '/card-details'\n" +
#       'Then the response should not contain the full credit card number',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Security Testing
    * url ZBIO_5213_026A11B060_URL
    Given path '/card-details'
    When method get
    Then status 200
    And match response.cardNumberPartial == '#string'
