# ********RoostGPT********

# Test generated by RoostGPT for test apikarate using AI Type Open AI and AI Model gpt-4o
# 
# ROOST_METHOD_HASH=4c18d38af9
# ROOST_METHOD_SIG_HASH=b6647e3748
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credit Card Notifications and Alerts',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Usability Testing',
#     steps: "Given the API base URL 'http://localhost:3000'\n" +
#       "When I send a GET request to '/notifications'\n" +
#       'Then the notifications should contain clear and understandable content',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credit Card Notifications and Alerts

  Background:
    * def ZBIO_5213_026A11B060_URL = karate.properties['ZBIO_5213_026A11B060_URL'] || karate.get('ZBIO_5213_026A11B060_URL', 'http://localhost:4010')

  Scenario: Usability Testing
    * url ZBIO_5213_026A11B060_URL
    Given path '/notifications'
    When method get
    Then status 200
    And match response == '#object'
